// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFnpjOgjFO0VFbE1HvmpuJKBdgp-Qa744',
    appId: '1:243219494581:android:4a9e95af16cd346def70fc',
    messagingSenderId: '243219494581',
    projectId: 'rffrrfrere',
    databaseURL: 'https://rffrrfrere-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rffrrfrere.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGiKcLR4W3WRL4u5V4ZLC4RxIkodhYboA',
    appId: '1:243219494581:ios:c2d8a69c54301ce1ef70fc',
    messagingSenderId: '243219494581',
    projectId: 'rffrrfrere',
    databaseURL: 'https://rffrrfrere-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rffrrfrere.firebasestorage.app',
    iosBundleId: 'com.example.untitled14',
  );
}
